package com.oneasad.socialapp.presentation.screens

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.material3.Button
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.material3.TextField
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.unit.dp
import androidx.navigation.NavController
import com.oneasad.socialapp.data.local.LocalPost
import com.oneasad.socialapp.presentation.PostViewModel
import org.koin.androidx.compose.koinViewModel


@Composable
fun CreatePostScreen(
    onPostCreated: (LocalPost) -> Unit,
    modifier: Modifier
) {
    var title by remember { mutableStateOf("") }
    var body by remember { mutableStateOf("") }
    var userId by remember { mutableStateOf("") }  // State for userId

    Column(
        modifier = modifier
            .fillMaxSize()
            .padding(16.dp),
        verticalArrangement = Arrangement.spacedBy(8.dp)
    ) {
        Text(text = "Create New Post", style = MaterialTheme.typography.headlineMedium)

        // Input for userId
        TextField(
            value = userId,
            onValueChange = { userId = it },
            label = { Text("User ID") },
            keyboardOptions = KeyboardOptions.Default.copy(keyboardType = KeyboardType.Number),
            singleLine = true
        )

        TextField(
            value = title,
            onValueChange = { title = it },
            label = { Text("Title") }
        )

        TextField(
            value = body,
            onValueChange = { body = it },
            label = { Text("Body") },
            modifier = Modifier.height(150.dp)
        )

        Button(
            onClick = {
                // Validate userId before proceeding
                if (userId.isNotEmpty() && title.isNotEmpty() && body.isNotEmpty()) {
                    onPostCreated(
                        LocalPost(
                            userId = userId.toInt(),  // Convert userId to Int
                            id = 0,                   // Assuming id is auto-generated by Room
                            title = title,
                            body = body
                        )
                    )
                }
            },
            enabled = title.isNotEmpty() && body.isNotEmpty() && userId.isNotEmpty()
        ) {
            Text("Post")
        }
    }
}
